In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('output/db/db.sqlite')
df = pd.read_sql_query(
    'SELECT repository, score_env, score_data, score_docs, score_code, score_repro, score_total '
    'FROM repositories ORDER BY score_total DESC',
    conn
)
conn.close()
df

,repository,score_env,score_data,score_docs,score_code,score_repro,score_total
0,impy-project/chromo,1.0,4.0,4.0,4.0,4.0,17.0
1,KevinMcK95/gaia_roman_astrometry,0.0,3.0,3.0,2.0,2.0,10.0
2,yt-project/libyt,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('output/db/db.sqlite')
conn.execute("ATTACH DATABASE 'data/db.sqlite' AS input_db")

df = pd.read_sql_query('''
    SELECT 
        r.repository,
        r.score_env, r.score_data, r.score_docs, 
        r.score_code, r.score_repro, r.score_total,
        'https://doi.org/' || a.doi AS paper_link
    FROM repositories r
    LEFT JOIN input_db.repositories ir ON r.repository = ir.repository
    LEFT JOIN input_db.article a ON ir.article_id = a.id
    ORDER BY r.score_total DESC
''', conn)

conn.close()
df

,repository,score_env,score_data,score_docs,score_code,score_repro,score_total,paper_link
0,impy-project/chromo,1.0,4.0,4.0,4.0,4.0,17.0,https://doi.org/10.1016/j.cpc.2026.110031
1,KevinMcK95/gaia_roman_astrometry,0.0,3.0,3.0,2.0,2.0,10.0,https://doi.org/10.1088/1538-3873/ae5a73
2,yt-project/libyt,NaN,NaN,NaN,NaN,NaN,NaN,https://doi.org/10.3847/1538-4365/ae5640

In [7]:
import sqlite3
conn = sqlite3.connect('data/db.sqlite')
for row in conn.execute("PRAGMA table_info(article)").fetchall():
    print(row)
conn.close()

(0, 'id', 'INTEGER', 0, None, 1)
(1, 'journal_id', 'INTEGER', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'pmid', 'TEXT', 0, None, 0)
(4, 'pmc', 'TEXT', 0, None, 0)
(5, 'publisher_id', 'TEXT', 0, None, 0)
(6, 'doi', 'TEXT', 0, None, 0)
(7, 'subject', 'TEXT', 0, None, 0)
(8, 'published_date', 'TEXT', 0, None, 0)
(9, 'received_date', 'TEXT', 0, None, 0)
(10, 'accepted_date', 'TEXT', 0, None, 0)
(11, 'license_type', 'TEXT', 0, None, 0)
(12, 'copyright_statement', 'TEXT', 0, None, 0)
(13, 'keywords', 'TEXT', 0, None, 0)
(14, 'repositories', 'TEXT', 0, None, 0)
(15, 'notebook_category', 'TEXT', 0, None, 0)